# -*- coding: utf-8 -*-
"""Biking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bx15RvkPiftLlZADpjYN6HmtD0WbV6oa
"""

!pip install pandas
!pip install kaggle

import os
from google.colab import files
os.makedirs('/root/.kaggle', exist_ok=True)

print("Please upload your kaggle.json file:")
uploaded = files.upload()

for filename in uploaded.keys():
  os.rename(filename, '/root/.kaggle/' + filename)
os.chmod('/root/.kaggle/kaggle.json', 0o600)

print("\nKaggle API key uploaded and configured successfully!")
print("You can now use the Kaggle API.")

import pandas as pd
import zipfile
import kaggle

!kaggle datasets download -d hmavrodiev/london-bike-sharing-dataset

zipfile_name = 'london-bike-sharing-dataset.zip'
with zipfile.ZipFile(zipfile_name, 'r') as file:
    file.extractall()

bikes = pd.read_csv("london_merged.csv")

bikes.info()

bikes.shape

bikes

bikes.weather_code.value_counts()

bikes.season.value_counts()

new_cols_dict ={
    'timestamp':'time',
    'cnt':'count',
    't1':'temp_real_C',
    't2':'temp_feels_like_C',
    'hum':'humidity_percent',
    'wind_speed':'wind_speed_kph',
    'weather_code':'weather',
    'is_holiday':'is_holiday',
    'is_weekend':'is_weekend',
    'season':'season'
}

bikes.rename(new_cols_dict, axis=1, inplace=True)

bikes.humidity_percent = bikes.humidity_percent / 100

season_dict = {
    '0.0':'spring',
    '1.0':'summer',
    '2.0':'autumn',
    '3.0':'winter'
}

weather_dict = {
    '1.0':'Clear',
    '2.0':'Scattered clouds',
    '3.0':'Broken clouds',
    '4.0':'Cloudy',
    '7.0':'Rain',
    '10.0':'Rain with thunderstorm',
    '26.0':'Snowfall'
}

bikes.season = bikes.season.astype('str')
bikes.season = bikes.season.map(season_dict)
bikes.weather = bikes.weather.astype('str')
bikes.weather = bikes.weather.map(weather_dict)

bikes.head()

bikes.to_excel('london_bikes_final.xlsx', sheet_name='Data')